apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6iv8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-6iv8@sha256:d19a80eee5b121fc511aec8685fb524ff5d33684b48a3909d21c662bf28cc973
        name: my-nodejs
        resources: {}
status: {}
